In [1]:
text_file = open('census_cost.txt') # Open file on read mode
line_list = text_file.read().splitlines() # List with stripped line-breaks
text_file.close()

In [2]:
line_list

['Source: https://www.genealogybranches.com/censuscosts.html',
 'Census Year\tTotal Population\tCensus Cost\tAverage Cost Per Person',
 '1790\t3,929,214\t$44,377\t1.13 cents',
 '1800\t5,308,483\t$66,109\t1.24 cents',
 '1810\t7,239,881\t$178,445\t2.46 cents',
 '1820\t9,633,822\t$208,526\t2.16 cents',
 '1830\t12,866,020\t$378,545\t2.94 cents',
 '1840\t17,069,458\t$833,371\t4.88 cents',
 '1850\t23,191,876\t$1,423,351\t6.14 cents',
 '1860\t31,443,321\t$1,969,377\t6.26 cents',
 '1870\t38,558,371\t$3,421,198\t8.87 cents',
 '1880\t50,155,783\t$5,790,678\t11.54 cents',
 '1890\t62,979,766\t$11,547,127\t18.33 cents',
 '1900\t76,303,387\t$11,854,000\t15.54 cents',
 '1910\t91,972,266\t$15,968,000\t17.07 cents',
 '1920\t105,710,620\t$25,117,000\t23.76 cents',
 '1930\t122,775,046\t$40,156,000\t32.71 cents',
 '1940\t131,669,275\t$67,527,000\t51.29 cents',
 '1950\t151,325,798\t$91,462,000\t60.44 cents',
 '1960\t179,323,175\t$127,934,000\t71.34 cents',
 '1970\t203,302,031\t$247,653,000\t$1.22',
 '1980\t226,542,199\t$1,078,488,000\t$4.76',
 '1990\t248,718,301\t$2,492,830,000\t$10.02',
 '2000\t281,421,906\t$4.5 Billion\t$15.99',
 '2010*\t308,745,538\t$13 Billion\t$42.11']

In [3]:
top2_list = line_list[:2]
top2_list

['Source: https://www.genealogybranches.com/censuscosts.html',
 'Census Year\tTotal Population\tCensus Cost\tAverage Cost Per Person']

In [4]:
data_list = line_list[2:]
data_list

['1790\t3,929,214\t$44,377\t1.13 cents',
 '1800\t5,308,483\t$66,109\t1.24 cents',
 '1810\t7,239,881\t$178,445\t2.46 cents',
 '1820\t9,633,822\t$208,526\t2.16 cents',
 '1830\t12,866,020\t$378,545\t2.94 cents',
 '1840\t17,069,458\t$833,371\t4.88 cents',
 '1850\t23,191,876\t$1,423,351\t6.14 cents',
 '1860\t31,443,321\t$1,969,377\t6.26 cents',
 '1870\t38,558,371\t$3,421,198\t8.87 cents',
 '1880\t50,155,783\t$5,790,678\t11.54 cents',
 '1890\t62,979,766\t$11,547,127\t18.33 cents',
 '1900\t76,303,387\t$11,854,000\t15.54 cents',
 '1910\t91,972,266\t$15,968,000\t17.07 cents',
 '1920\t105,710,620\t$25,117,000\t23.76 cents',
 '1930\t122,775,046\t$40,156,000\t32.71 cents',
 '1940\t131,669,275\t$67,527,000\t51.29 cents',
 '1950\t151,325,798\t$91,462,000\t60.44 cents',
 '1960\t179,323,175\t$127,934,000\t71.34 cents',
 '1970\t203,302,031\t$247,653,000\t$1.22',
 '1980\t226,542,199\t$1,078,488,000\t$4.76',
 '1990\t248,718,301\t$2,492,830,000\t$10.02',
 '2000\t281,421,906\t$4.5 Billion\t$15.99',
 '2010*\t308,745,538\t$13 Billion\t$42.11']

In [5]:
data_list[-1][:4]

'2010'

In [6]:
year_list = []
for i in range(len(data_list)):
    year_list.append(data_list[i][:4])
year_list

['1790',
 '1800',
 '1810',
 '1820',
 '1830',
 '1840',
 '1850',
 '1860',
 '1870',
 '1880',
 '1890',
 '1900',
 '1910',
 '1920',
 '1930',
 '1940',
 '1950',
 '1960',
 '1970',
 '1980',
 '1990',
 '2000',
 '2010']

In [7]:
pop_list = []
temp_lst = []
for i in range(len(data_list)):
    temp_string = data_list[i].replace("\t", "    ")
    temp_string = temp_string.replace(",","")
    temp_lst.append(temp_string[8:17])
for i in range(len(temp_lst)):
    pop_list.append(temp_lst[i].replace(" ",""))
pop_list

['3929214',
 '5308483',
 '7239881',
 '9633822',
 '12866020',
 '17069458',
 '23191876',
 '31443321',
 '38558371',
 '50155783',
 '62979766',
 '76303387',
 '91972266',
 '105710620',
 '122775046',
 '131669275',
 '151325798',
 '179323175',
 '203302031',
 '226542199',
 '248718301',
 '281421906',
 '30874553']

In [8]:
data_list[2][17:]
data_list[0].split('\t')[3]

'1.13 cents'

In [9]:
cost_list = []
temp_string=''
for i in range(len(data_list)):
    temp_string=data_list[i].split('\t')[2]
    temp_string = temp_string.replace("$","")
    temp_string = temp_string.replace(",","")
    temp_string = temp_string.replace(" Billion","000000000")
    
    cost_list.append(temp_string)

cost_list

['44377',
 '66109',
 '178445',
 '208526',
 '378545',
 '833371',
 '1423351',
 '1969377',
 '3421198',
 '5790678',
 '11547127',
 '11854000',
 '15968000',
 '25117000',
 '40156000',
 '67527000',
 '91462000',
 '127934000',
 '247653000',
 '1078488000',
 '2492830000',
 '4.5000000000',
 '13000000000']

In [10]:
#Extract the "Average Cost per Person" column from the data_list and assign them to a list named "avg_list". Remove the "cents", and "$". Make sure to divide the numbers in cents by 100 so that all numbers are measured in dollar. Print the cleansed avg_list.
avg_list = []
temp_string=''
for i in range(len(data_list)):
    temp_string=data_list[i].split('\t')[3]
    temp_string = temp_string.replace("$","")
    if ' cents' in temp_string:
        temp_string=temp_string.replace(" cents","")
        l1=float(temp_string)/100
        avg_list.append(l1)
    else:
    
        temp_string
        avg_list.append(float(temp_string))

avg_list

[0.0113,
 0.0124,
 0.0246,
 0.0216,
 0.0294,
 0.048799999999999996,
 0.061399999999999996,
 0.0626,
 0.08869999999999999,
 0.11539999999999999,
 0.1833,
 0.15539999999999998,
 0.1707,
 0.2376,
 0.3271,
 0.5129,
 0.6043999999999999,
 0.7134,
 1.22,
 4.76,
 10.02,
 15.99,
 42.11]

In [11]:
a1=top2_list[1].split('\t')
a1

['Census Year', 'Total Population', 'Census Cost', 'Average Cost Per Person']

In [12]:
import pandas as pd
data=pd.DataFrame(columns =a1 )
data

Empty DataFrame
Columns: [Census Year, Total Population, Census Cost, Average Cost Per Person]
Index: []

In [13]:
data['Census Year'] = year_list
data['Total Population'] = pop_list
data['Census Cost']= cost_list
data['Average Cost Per Person']= avg_list

In [14]:
data

   Census Year Total Population   Census Cost  Average Cost Per Person
0         1790          3929214         44377                   0.0113
1         1800          5308483         66109                   0.0124
2         1810          7239881        178445                   0.0246
3         1820          9633822        208526                   0.0216
4         1830         12866020        378545                   0.0294
5         1840         17069458        833371                   0.0488
6         1850         23191876       1423351                   0.0614
7         1860         31443321       1969377                   0.0626
8         1870         38558371       3421198                   0.0887
9         1880         50155783       5790678                   0.1154
10        1890         62979766      11547127                   0.1833
11        1900         76303387      11854000                   0.1554
12        1910         91972266      15968000                   0.1707
13        1920        105710620      25117000                   0.2376
14        1930        122775046      40156000                   0.3271
15        1940        131669275      67527000                   0.5129
16        1950        151325798      91462000                   0.6044
17        1960        179323175     127934000                   0.7134
18        1970        203302031     247653000                   1.2200
19        1980        226542199    1078488000                   4.7600
20        1990        248718301    2492830000                  10.0200
21        2000        281421906  4.5000000000                  15.9900
22        2010         30874553   13000000000                  42.1100

In [15]:
file = open('census_cost.csv', 'a')

# a list of links:
file.write(top2_list[0] + '\n')

file.close()  
data.to_csv('census_cost.csv')

In [16]:
import pandas as pd
csv_file = pd.read_csv("census_cost.csv")
csv_file

,Unnamed: 0,Census Year,Total Population,Census Cost,Average Cost Per Person
0,0,1790,3929214,4.437700e+04,0.0113
1,1,1800,5308483,6.610900e+04,0.0124
2,2,1810,7239881,1.784450e+05,0.0246
3,3,1820,9633822,2.085260e+05,0.0216
4,4,1830,12866020,3.785450e+05,0.0294
5,5,1840,17069458,8.333710e+05,0.0488
6,6,1850,23191876,1.423351e+06,0.0614
7,7,1860,31443321,1.969377e+06,0.0626
8,8,1870,38558371,3.421198e+06,0.0887
9,9,1880,50155783,5.790678e+06,0.1154
10,10,1890,62979766,1.154713e+07,0.1833
11,11,1900,76303387,1.185400e+07,0.1554
12,12,1910,91972266,1.596800e+07,0.1707
13,13,1920,105710620,2.511700e+07,0.2376
14,14,1930,122775046,4.015600e+07,0.3271
15,15,1940,131669275,6.752700e+07,0.5129
16,16,1950,151325798,9.146200e+07,0.6044
17,17,1960,179323175,1.279340e+08,0.7134
18,18,1970,203302031,2.476530e+08,1.2200
19,19,1980,226542199,1.078488e+09,4.7600
20,20,1990,248718301,2.492830e+09,10.0200
21,21,2000,281421906,4.500000e+00,15.9900
22,22,2010,30874553,1.300000e+10,42.1100

In [17]:
# Cov = pd.read_csv("census_cost.txt")
# Frame=pd.DataFrame(Cov, columns = top2_list)
# Frame.to_csv("census_cost.csv", sep='\t')

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=3f410f9c-f9c1-4028-8b9a-07adb94010da' target="_blank">
<img style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>